[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npx serve -s dist"]

[build.environment]
NODE_ENV = "production"

[build.args]
VITE_API_BASE_URL = "https://wingman-dev.up.railway.app"
