[build]
builder = "DOCKERFILE"
buildCommand = ""
watchPatterns = ["frontend/**"]

[deploy]
startCommand = ""

[environment]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://wingman-dev.up.railway.app"

