[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "npx serve -s dist"

[env]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://wingman-dev.up.railway.app"

