"""Add level and feedback fields

Revision ID: 74c2e2d6b600
Revises: 9049b82aed0d
Create Date: 2025-04-24 12:59:13.005019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c2e2d6b600'
down_revision = '9049b82aed0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure old level table is removed to avoid duplicate
    op.execute("DROP TABLE IF EXISTS level;")
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('student_feedback', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wingfoil_level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_wingfoil_level_id', 'level', ['wingfoil_level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_wingfoil_level_id', type_='foreignkey')
        batch_op.drop_column('wingfoil_level_id')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('student_feedback')
        batch_op.drop_column('instructor_feedback')

    op.drop_table('level')
    # ### end Alembic commands ###
